### ISSUE TITLE
Twitter link does not work

### ISSUE THREAD

**Issue by eddiejaoude** [goupaz/goupaz.com#218]
404 https://twitter.com/goupaz

**Comment by sakomws** [comment]
hey @eddiejaoude I messed up on it :) Was changing the birth date to be 2 years old, and twitter blocked it. I raised a support ticket to fix it :) Sorry, i know it sucks ;)

**Comment by eddiejaoude** [comment]
no worries 🤓

**Comment by sakomws** [comment]
it is back online @eddiejaoude !

**Comment by eddiejaoude** [comment]
Great 👍
